@DeskFlow_API_HostAddress = http://localhost:5285

### Listar categorias

GET {{DeskFlow_API_HostAddress}}/api/categorias/
Accept: application/json

###

### Criar categoria

POST {{DeskFlow_API_HostAddress}}/api/categorias
Content-Type: application/json

{
  "nome": "Teste Chamado"
}

###

### Buscar categoria por Id

GET {{DeskFlow_API_HostAddress}}/api/categorias/8
Accept: application/json
###

### Atualizar categoria

PUT {{DeskFlow_API_HostAddress}}/api/categorias/9
Content-Type: application/json

{
  "nome": "Hardware e Periféricos"
}

###

### Excluir categoria

DELETE {{DeskFlow_API_HostAddress}}/api/categorias/6
Accept: application/json

### Criar chamado

POST {{DeskFlow_API_HostAddress}}/api/chamados
Content-Type: application/json

{
  "titulo": "Computador não liga",
  "descricao": "Computador da sala 12 não apresenta sinal de energia.",
  "prioridade": "Alta",
  "solicitanteNome": "Ana",
  "categoriaId": 9
}

### Listar chamados

GET {{DeskFlow_API_HostAddress}}/api/chamados
Accept: application/json

###

### Buscar chamado por Id

GET {{DeskFlow_API_HostAddress}}/api/chamados/1
Accept: application/json

###

### Iniciar atendimento do chamado

POST {{DeskFlow_API_HostAddress}}/api/chamados/1/iniciar

### Encerrar chamado

POST {{DeskFlow_API_HostAddress}}/api/chamados/2/encerrar
Content-Type: application/json

{
  "solucao": ""
}
### Confirmar encerramento do chamado
GET {{DeskFlow_API_HostAddress}}/api/chamados/1
Accept: application/json


###Tentando encerrar chamado já encerrado
POST {{DeskFlow_API_HostAddress}}/api/chamados/1/encerrar
Content-Type: application/json

{
  "solucao": "Outro texto"
}