@DeskFlow_API_HostAddress = http://localhost:5285

### Listar categorias

GET {{DeskFlow_API_HostAddress}}/api/categorias/
Accept: application/json

###

### Criar categoria

POST {{DeskFlow_API_HostAddress}}/api/categorias
Content-Type: application/json

{
  "nome": "Teste Chamado"
}

###

### Buscar categoria por Id

GET {{DeskFlow_API_HostAddress}}/api/categorias/8
Accept: application/json
###

### Atualizar categoria

PUT {{DeskFlow_API_HostAddress}}/api/categorias/8
Content-Type: application/json

{
  "nome": "Hardware e Periféricos"
}

###

### Excluir categoria

DELETE {{DeskFlow_API_HostAddress}}/api/categorias/6
Accept: application/json

### Criar chamado

POST {{DeskFlow_API_HostAddress}}/api/chamados
Content-Type: application/json

{
  "titulo": "Computador não liga",
  "descricao": "Computador da sala 12 não apresenta sinal de energia.",
  "prioridade": "Alta",
  "solicitanteNome": "Ana",
  "categoriaId": 8
}